import "./globals.css";
import { KakaoProvider } from "@/context/KakaoContext";

export const metadata = {
  title: "모바일 청첩장",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className="h-full">
      <head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        />
      </head>
      <body className="main-container flexcenter flex-col antialiased ">
        <KakaoProvider>
          <main
            className="page-main p-6 text-center bg-cover"
            style={{
              border: "1px solid #eaeaea",
            }}
          >
            {children}
          </main>
        </KakaoProvider>
      </body>
    </html>
  );
}
