import "./globals.css";
import Script from "next/script";

export const metadata = {
  title: "청첩장",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className="h-full">
      <head>
        <meta
          httpEquiv="Content-Security-Policy"
          content="upgrade-insecure-requests"
        />
        {/* 카카오 SDK와 맵 SDK 스크립트를 비동기적으로 로드 */}
        <Script
          src="https://developers.kakao.com/sdk/js/kakao.js"
          strategy="beforeInteractive" // 페이지 렌더링 후에 로드
        />
        <Script
          type="text/javascript"
          src={`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_API_KEY}&autoload=false&libraries=services`}
          strategy="beforeInteractive" // 페이지 렌더링 후에 로드
        />
      </head>

      <body className="main-container flexcenter flex-col antialiased ">
        <main
          className="page-main p-6 text-center bg-cover"
          // style={{
          //   backgroundImage: `url('https://deardeer.kr/uploads/product-detail/images/2018/03/27/thumb3_img_36cba51bf048922fac01_cp.png')`,
          // }}
          style={{
            border: "1px solid #eaeaea",
          }}
        >
          {children}
        </main>
      </body>
    </html>
  );
}
